GET http://localhost:3005/api/blogs

###
# GET http://localhost:3005/api/blogs/6169adae4306900da455af35
GET http://localhost:3005/api/blogs/someBogusId

###
POST http://localhost:3005/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJpZ1JlZCIsImlkIjoiNjE2ZGIyZTcwNzQ5ODYxM2VhNjRmYTdkIiwiaWF0IjoxNjM0NzU3ODA2fQ.6GPMvlwckubxi6Y-3GXcfbYT6mQ2whzs15HLJFZzLoM

{
  "author": "Me!",
  "title": "And I've got an auth token!"
}

###
PUT http://localhost:3005/api/blogs/e
Content-Type: application/json

{
  "author": "Jimmy TwoLon",
  "title": "How 2 basic",
  "likes": 3
}

###
DELETE http://localhost:3005/api/blogs/616d7fd2605cbee5b37c9a65