GET http://localhost:3005/api/blogs

###
# GET http://localhost:3005/api/blogs/6169adae4306900da455af35
GET http://localhost:3005/api/blogs/someBogusId

###
POST http://localhost:3005/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRvbSIsImlkIjoiNjE3MDk0NmIzMjM2ZDRhNWRmNzg3YjYxIiwiaWF0IjoxNjM0NzY3OTkzfQ.adzLYbXotYsNtFU1cnjZ-_sglWuh-bGPpQkZerlSj3o
# Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJpZ1JlZCIsImlkIjoiNjE2ZGIyZTcwNzQ5ODYxM2VhNjRmYTdkIiwiaWF0IjoxNjM0NzU3ODA2fQ.6GPMvlwckubxi6Y-3GXcfbYT6mQ2whzs15HLJFZzLoM

{
  "author": "bingpot",
  "title": "b99 captain holt"
}

###
PUT http://localhost:3005/api/blogs/6171ce032fd4bc228cf08176
Content-Type: application/json

{
  "title":	"working with togglables",
  "author":	"Mr. Mime",
  "likes":	1
}
###
DELETE http://localhost:3005/api/blogs/61717078974e939fcbfeb1c7
# bigRed
# Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJpZ1JlZCIsImlkIjoiNjE2ZGIyZTcwNzQ5ODYxM2VhNjRmYTdkIiwiaWF0IjoxNjM0NzU3ODA2fQ.6GPMvlwckubxi6Y-3GXcfbYT6mQ2whzs15HLJFZzLoM
# tom
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRvbSIsImlkIjoiNjE3MDk0NmIzMjM2ZDRhNWRmNzg3YjYxIiwiaWF0IjoxNjM0NzY3OTkzfQ.adzLYbXotYsNtFU1cnjZ-_sglWuh-bGPpQkZerlSj3o


###
POST http://localhost:3005/api/blogs/617abae5bd5212279342e4db/comments
Content-Type: application/json

{
  "comment": ""
}